apiVersion: v1
kind: Service
metadata:
  name: service-rabbitmq
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
    rel: stable